auth_enabled: false

server:
  http_listen_port: 3100

common:
  instance_addr: 127.0.0.1
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

schema_config:
  configs:
    - from: 2020-10-24
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

# Increase ingestion limits
limits_config:
  ingestion_rate_mb: 64          # Default is 4MB/sec, increase to 64MB/sec
  ingestion_burst_size_mb: 128   # Default is 6MB, increase to 128MB
  max_streams_per_user: 10000    # Default is 10000
  max_line_size: 256000          # Default is 256KB
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  max_query_series: 500

ruler:
  alertmanager_url: http://localhost:9093